"""Add failed AnswerType

Revision ID: 34ede583926d
Revises: fd8e31746245
Create Date: 2023-11-12 19:56:40.089945

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34ede583926d"
down_revision: Union[str, None] = "fd8e31746245"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    answer_type_enum = sa.Enum(
        "ai", "blocked", "template", "unanswered", "failed", name="answertype"
    )
    op.alter_column(
        "conversations", "answer_type", type_=answer_type_enum, existing_type=sa.Enum
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    answer_type_enum = sa.Enum(
        "ai", "blocked", "template", "unanswered", name="answertype"
    )
    op.alter_column(
        "conversations", "answer_type", type_=answer_type_enum, existing_type=sa.Enum
    )
    # ### end Alembic commands ###
