"""Initial migration

Revision ID: c21ec4c5d415
Revises: 
Create Date: 2023-09-24 10:39:12.180443

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c21ec4c5d415"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("is_vectorized", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("registered_at", sa.DateTime(), nullable=False),
        sa.Column("city", sa.Enum("Torino", name="cityenum"), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("is_closed_mon", sa.Boolean(), nullable=False),
        sa.Column("is_closed_tue", sa.Boolean(), nullable=False),
        sa.Column("is_closed_wed", sa.Boolean(), nullable=False),
        sa.Column("is_closed_thu", sa.Boolean(), nullable=False),
        sa.Column("is_closed_fri", sa.Boolean(), nullable=False),
        sa.Column("is_closed_sat", sa.Boolean(), nullable=False),
        sa.Column("is_closed_sun", sa.Boolean(), nullable=False),
        sa.Column("is_during_day", sa.Boolean(), nullable=False),
        sa.Column("is_during_night", sa.Boolean(), nullable=False),
        sa.Column("is_countryside", sa.Boolean(), nullable=False),
        sa.Column("is_for_children", sa.Boolean(), nullable=False),
        sa.Column("is_for_disabled", sa.Boolean(), nullable=False),
        sa.Column("is_for_animals", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.Column("block_expires_at", sa.DateTime(), nullable=True),
        sa.Column("registered_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_phone_number"), "users", ["phone_number"], unique=False
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("wa_id", sa.String(), nullable=False),
        sa.Column("from_message", sa.String(), nullable=False),
        sa.Column("to_message", sa.String(), nullable=True),
        sa.Column(
            "answer_type",
            sa.Enum(
                "ai",
                "blocked",
                "failed",
                "conversational",
                "template",
                "unanswered",
                name="answertype",
            ),
            nullable=False,
        ),
        sa.Column("used_event_ids", sa.String(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("registered_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversations_wa_id"), "conversations", ["wa_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversations_wa_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_users_phone_number"), table_name="users")
    op.drop_table("users")
    op.drop_table("events")
    # ### end Alembic commands ###
