"""Add price level

Revision ID: fd8e31746245
Revises: f6f982dab819
Create Date: 2023-10-13 21:50:13.657880

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd8e31746245"
down_revision: Union[str, None] = "f6f982dab819"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

PriceLevelEnum = sa.Enum(
    "free", "inexpensive", "moderate", "expensive", "very_expensive", name="pricelevel"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    PriceLevelEnum.create(op.get_bind(), checkfirst=True)
    op.add_column("events", sa.Column("price_level", PriceLevelEnum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "price_level")
    PriceLevelEnum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
